# General
import os

CLIENT_ID = os.getenv('CLIENT_ID', '123')

NEQUI_CHANNEL_DEPOSIT_WITHDRAWALS = os.getenv('NEQUI_CHANNEL_DEPOSIT_WITHDRAWALS', 'MF-001')
NEQUI_CHANNEL_QR_PAYMENTS = os.getenv('NEQUI_CHANNEL_QR_PAYMENTS', 'PQR03-C001')

# Status Codes
NEQUI_STATUS_CODE_SUCCESS = '0'
NEQUI_STATUS_DESC_SUCCESS = 'SUCCESS'


NEQUI_PAYMENT_STATUS_CODE_PENDING = '33'
NEQUI_PAYMENT_STATUS_DESC_PENDING = 'PENDING'
NEQUI_PAYMENT_STATUS_CODE_SUCCESS = '35'
NEQUI_PAYMENT_STATUS_DESC_SUCCESS = 'SUCCESS'

NEQUI_PAYMENT_STATUS_DESC_UNKNOWN = 'UNKNOWN'
